### PR TITLE
Move Metrics, BackgroundJob and Dashboard enabling to runtime configuration

### PR DESCRIPTION
**Pull request by prabhjotlalli**

### CODE REVIEW

**Comment by rdehuyss** [comment]
@cla-bot check

**Comment by rdehuyss** [comment]
Pinging @tms0 as he originally split some of the build and runtime configuration for Quarkus. 

More info here in PR https://github.com/jobrunr/jobrunr/pull/845.

**Comment by auloin** [comment]
Hi @prabhjotlalli, did you have time to test this locally, for native build as well? I wonder what would happen if `quarkus.jobrunr.background-job-server.enabled=false` at build time, is it possible to enable it at runtime?

**Comment by rdehuyss** [comment]
If we want to do this following Quarkus best practices, I think we must look into [Quarkus re-augmentation](https://quarkus.io/guides/reaugmentation). See also https://github.com/jobrunr/jobrunr/pull/845#issuecomment-2317370600.

@prabhjotlalli - do you have any experience with re-augementation?

**Pull request closed without merging**
