### PR TITLE
Raise log level for JobZooKeeper run exceeding poll interval.

### PR DESCRIPTION
**Pull request by tan9**
The `ZooKeeperStatistics` class has been updated to raise the log level for events where the `JobZooKeeper` run exceeds the poll interval. This change will make these events more noticeable in the log files.

### CODE REVIEW

**Comment by rdehuyss** [comment]
Hi @tan9 , most of our developments are now targeting v7 and we try to minimise releases of v6. Can we put this in the v7 branch or do you need it urgently?

**Comment by tan9** [comment]
@rdehuyss, it's alright to postpone it until the v7 release since we've already resolved the issue we encountered 😄

**Comment by rdehuyss** [comment]
FYI - we're also changing the 'JobRunr Engine' and I don't think you will encounter this anymore.

**Comment by rdehuyss** [comment]
Closing as improvements to engine and logging were done.

**Pull request closed without merging**
