### PR TITLE
Feature/fixing quarkus support for quarkus 3.x

### PR DESCRIPTION
**Pull request by ShiboTanany**

### CODE REVIEW

**Comment by rdehuyss** [comment]
Hi @ShiboTanany - can you sign the contributor agreement? Then I can review the PR.

**Comment by ShiboTanany** [comment]
@rdehuyss  i didn't find the link of agreement of contribution in contributing.md

**Comment by bmertens911** [comment]
Hi @ShiboTanany - I just had another idea: are you willing to use a beta of JobRunr v7 which already contains the bugfix? If so, I can release a beta with the fix already in it. Although still a beta, it is really wel tested. There will some small breaking changes still going in v7 but only related to configuration.

**Comment by rdehuyss** [comment]
Hi @ShiboTanany - I just had another idea: are you willing to use a beta of JobRunr v7 which already contains the bugfix? If so, I can release a beta with the fix already in it. Although still a beta, it is really wel tested. There will some small breaking changes still going in v7 but only related to configuration.

**Comment by ShiboTanany** [comment]
> Hi @ShiboTanany - I just had another idea: are you willing to use a beta of JobRunr v7 which already contains the bugfix? If so, I can release a beta with the fix already in it. Although still a beta, it is really wel tested. There will some small breaking changes still going in v7 but only related to configuration.

i can do the both , try version 7 and having the first changes to be in Jobrunr <3

**Review by rdehuyss — APPROVED** [review]

**Pull request merged**
