### PR TITLE
Add support for GraalVM Native executable with Quarkus

### LINKED ISSUE #831: [BUG] Unable to build a quarkus native application (com.oracle.graal.pointsto.constraints.UnresolvedElementException: Discovered unresolved type during parsing: oracle.sql.TIMESTAMP)
### JobRunr Version

6.3.0

### JDK Version

OpenJDK 17

### Your SQL / NoSQL database

N.A.

### What happened?

Unable to build a Quarkus native application, it fails with the following error : 

```
Caused by: com.oracle.graal.pointsto.constraints.UnresolvedElementException: Discovered unresolved type during parsing: oracle.sql.TIMESTAMP. This error is reported at image build time because class org.jobrunr.utils.reflection.autobox.InstantForOracleTypeAutoboxer is registered for linking at image build time by command line
```

Expected : The native image build is working.

### How to reproduce?

See this Github project : https://github.com/tms0/jobrunr-quarkus-native
For Building a native app (with Docker running) : `./gradlew build -Dquarkus.package.type=native -Dquarkus.native.container-build=true` 

### Relevant log output

_No response_

### PR DESCRIPTION
**Pull request by tms0**
Fixes #831 

This PR add support for GraalVM Native executable with Quarkus.

TODO:

- [x]  Add job request handler support

### CODE REVIEW

**Comment by rdehuyss** [comment]
Hi @tms0 ,

Thank you so much for this awesome PR! I'll continue the discussion from https://github.com/jobrunr/jobrunr/issues/831#issuecomment-1723112164 here.

In Spring Boot everything works when using `JobRequest` / `JobRequestHandler`. What I do there is during the native image build step, I search for all classes implementing `JobRequest` / `JobRequestHandler` and register them. This makes sure they can run in native mode.

Back when I added support for GraalVM, I did not know/find anything about `lambdaCapturingTypes`. Thanks for bringing this to my attention ❤️!

**Comment by tms0** [comment]
You're welcome, thank you for the library ;-)

> Back when I added support for GraalVM, I did not know/find anything about lambdaCapturingTypes. Thanks for bringing this to my attention ❤️!

The `lambdaCapturingTypes` thing is relatively recent (https://github.com/oracle/graal/commit/b455f23b624a1af149c7d5769443a4775bedd087 and https://github.com/quarkusio/quarkus/issues/28530), and there is almost nothing about this on the internet!

I will try to work on the  `JobRequest` / `JobRequestHandler` part tomorrow. Do you see other things to do?

**Comment by rdehuyss** [comment]
No, for me if the `JobRequest` / `JobRequestHandler` is added, all is well. I'll test locally and if all is well, it can be merged.

**Comment by tms0** [comment]
Hi @rdehuyss,

I added the missing pieces, and fixed some issues.
Note : I only tested with jsonb and MongoDB as a storage.

**Comment by rdehuyss** [comment]
@cla-bot check

**Comment by rdehuyss** [comment]
hi @tms0 - I only needed to do a small change to add support for SQL databases.

You can see the changes here: https://github.com/jobrunr/jobrunr/compare/master...pr-835. I also needed to register the `SQLStorageProviders` for reflection.

Up to you if I we you change this PR to include those changes or we close this PR and create a new one from branch PR-835.

Drop me a note with what you prefer.

**Comment by tms0** [comment]
Hi @rdehuyss,

Good to hear! You can close this one, it doesn't matter to me.

**Comment by rdehuyss** [comment]
Closing in favor for #841 .

**Pull request closed without merging**
