### PR TITLE
use DelayQueue (instead of polling every 250ms)

### PR DESCRIPTION
**Pull request by jloisel**
Instead of polling every 250ms, which is inefficient, use a daemon thread which constantly takes elements from a delay queue. It perfectly compensates for missed jobs.

### CODE REVIEW

**Comment by jloisel** [comment]
Please review as it may not necessarly pass unit tests (i'm used to maven, not gradle).

**Comment by rdehuyss** [comment]
Hi @jloisel !

Thanks for this PR! Do you have some time to discuss it during a short call?

**Comment by jloisel** [comment]
Hi, sorry didn't saw your message. I think it's a better approach using Delay Queue, but i'm not sure your fix is really fixing the #448 issue. I'm not an expert of how jobrunr works so... It's mostly based on the fact ScheduledExecutorService internally uses a DelayQueue too, and it works great to compensate for processing time while tasks to be executed are piling up.

**Comment by rdehuyss** [comment]
Hi @jloisel ,

I do think some stuff is not correct yet.

E.g. de `ServerZooKeeperTest.onStartServerAnnouncesItselfAndDoesNotBecomeMasterIfItIsNotTheFirstToBeOnline()`.

With my implementation it is:

```
20:35:59.184 [Test worker] INFO  o.j.s.t.ScheduledThreadPoolJobRunrExecutor - ThreadManager of type 'ScheduledThreadPoolJobRunrExecutor' started
20:35:59.191 [backgroundjob-worker-pool-2-thread-4] INFO  o.jobrunr.server.BackgroundJobServer - Found 0 recurring jobs that need to be updated.
20:35:59.435 [backgroundjob-zookeeper-pool-1-thread-2] INFO  o.jobrunr.server.BackgroundJobServer - JobRunr BackgroundJobServer (b9f74622-5146-4152-ade7-ec95c1b6528a) using InMemoryStorageProvider and 10 BackgroundJobPerformers started successfully
20:35:59.436 [backgroundjob-zookeeper-pool-1-thread-2] INFO  org.jobrunr.server.ServerZooKeeper - Server 2341812a-b576-45b2-8f92-fbd73fb9f275 is master (another BackgroundJobServer)
20:35:59.488 [Test worker] INFO  o.jobrunr.server.BackgroundJobServer - BackgroundJobServer and BackgroundJobPerformers - stopping (waiting for all jobs to complete - max 10 seconds)
20:35:59.488 [Test worker] INFO  o.j.s.t.ScheduledThreadPoolJobRunrExecutor - Shutting down ScheduledThreadPoolJobRunrExecutor
20:35:59.490 [Test worker] INFO  o.j.s.t.ScheduledThreadPoolJobRunrExecutor - Shutting down ScheduledThreadPoolJobRunrExecutor
20:35:59.491 [Test worker] INFO  o.jobrunr.server.BackgroundJobServer - BackgroundJobServer and BackgroundJobPerformers stopped
```

With your however, the polling happens constantly I have the impression.
```
20:34:54.507 [backgroundjob-zookeeper-pool-1-thread-1] ERROR org.jobrunr.server.ServerZooKeeper - JobRunr is passing the poll interval in seconds time-box. This means your poll interval in seconds setting is too small. This can result in an unstable cluster or recurring jobs that are skipped.
20:34:54.507 [backgroundjob-zookeeper-pool-1-thread-3] ERROR org.jobrunr.server.ServerZooKeeper - JobRunr is passing the poll interval in seconds time-box. This means your poll interval in seconds setting is too small. This can result in an unstable cluster or recurring jobs that are skipped.
20:34:54.509 [backgroundjob-zookeeper-pool-1-thread-2] INFO  o.jobrunr.server.BackgroundJobServer - JobRunr BackgroundJobServer (5e2d2489-dcf0-408b-9c3f-1bf292e2e95a) using InMemoryStorageProvider and 10 BackgroundJobPerformers started successfully
20:34:54.510 [backgroundjob-zookeeper-pool-1-thread-2] INFO  org.jobrunr.server.ServerZooKeeper - Server f17164fd-7839-499d-a871-3bb404f8a905 is master (another BackgroundJobServer)
20:34:54.512 [backgroundjob-zookeeper-pool-1-thread-1] ERROR org.jobrunr.server.ServerZooKeeper - JobRunr is passing the poll interval in seconds time-box. This means your poll interval in seconds setting is too small. This can result in an unstable cluster or recurring jobs that are skipped.
20:34:54.512 [backgroundjob-zookeeper-pool-1-thread-3] ERROR org.jobrunr.server.ServerZooKeeper - JobRunr is passing the poll interval in seconds time-box. This means your poll interval in seconds setting is too small. This can result in an unstable cluster or recurring jobs that are skipped.
20:34:54.512 [backgroundjob-zookeeper-pool-1-thread-1] ERROR org.jobrunr.server.ServerZooKeeper - JobRunr is passing the poll interval in seconds time-box. This means your poll interval in seconds setting is too small. This can result in an unstable cluster or recurring jobs that are skipped.
20:34:54.512 [backgroundjob-worker-pool-2-thread-4] INFO  o.jobrunr.server.BackgroundJobServer - Found 0 recurring jobs that need to be updated.
20:34:54.512 [backgroundjob-zookeeper-pool-1-thread-3] ERROR org.jobrunr.server.ServerZooKeeper - JobRunr is passing the poll interval in seconds time-box. This means your poll interval in seconds setting is too small. This can result in an unstable cluster or recurring jobs that are skipped.
20:34:54.513 [backgroundjob-zookeeper-pool-1-thread-3] ERROR org.jobrunr.server.ServerZooKeeper - JobRunr is passing the poll interval in seconds time-box. This means your poll interval in seconds setting is too small. This can result in an unstable cluster or recurring jobs that are skipped.
20:34:54.513 [backgroundjob-zookeeper-pool-1-thread-1] ERROR org.jobrunr.server.ServerZooKeeper - JobRunr is passing the poll interval in seconds time-box. This means your poll interval in seconds setting is too small. This can result in an unstable cluster or recurring jobs that are skipped.
20:34:54.513 [backgroundjob-zookeeper-pool-1-thread-3] ERROR org.jobrunr.server.ServerZooKeeper - JobRunr is passing the poll interval in seconds time-box. This means your poll interval in seconds setting is too small. This can result in an unstable cluster or recurring jobs that are skipped.
20:34:54.513 [backgroundjob-zookeeper-pool-1-thread-3] ERROR org.jobrunr.server.ServerZooKeeper - JobRunr is passing the poll interval in seconds time-box. This means your poll interval in seconds setting is too small. This can result in an unstable cluster or recurring jobs that are skipped.
20:34:54.513 [backgroundjob-zookeeper-pool-1-thread-1] ERROR org.jobrunr.server.ServerZooKeeper - JobRunr is passing the poll interval in seconds time-box. This means your poll interval in seconds setting is too small. This can result in an unstable cluster or recurring jobs that are skipped.
20:34:54.513 [backgroundjob-zookeeper-pool-1-thread-3] ERROR org.jobrunr.server.ServerZooKeeper - JobRunr is passing the poll interval in seconds time-box. This means your poll interval in seconds setting is too small. This can result in an unstable cluster or recurring jobs that are skipped.
20:34:54.513 [backgroundjob-zookeeper-pool-1-thread-2] ERROR org.jobrunr.server.ServerZooKeeper - JobRunr is passing the poll interval in seconds time-box. This means your poll interval in seconds setting is too small. This can result in an unstable cluster or recurring jobs that are skipped.
20:34:54.514 [backgroundjob-zookeeper-pool-1-thread-2] ERROR org.jobrunr.server.ServerZooKeeper - JobRunr is passing the poll interval in seconds time-box. This means your poll interval in seconds setting is too small. This can result in an unstable cluster or recurring jobs that are skipped.
20:34:54.514 [backgroundjob-zookeeper-pool-1-thread-2] ERROR org.jobrunr.server.ServerZooKeeper - JobRunr is passing the poll interval in seconds time-box. This means your poll interval in seconds setting is too small. This can result in an unstable cluster or recurring jobs that are skipped.
20:34:54.514 [backgroundjob-zookeeper-pool-1-thread-2] ERROR org.jobrunr.server.ServerZooKeeper - JobRunr is passing the poll interval in seconds time-box. This means your poll interval in seconds setting is too small. This can result in an unstable cluster or recurring jobs that are skipped.
20:34:54.514 [backgroundjob-zookeeper-pool-1-thread-1] ERROR org.jobrunr.server.ServerZooKeeper - JobRunr is passing the poll interval in seconds time-box. This means your poll interval in seconds setting is too small. This can result in an unstable cluster or recurring jobs that are skipped.
```

I'm now going into holidays but we could perhaps connect afterwards.

**Comment by jloisel** [comment]
Thx for the feedback, i'll check if I find why it doesn't work.

**Comment by rdehuyss** [comment]
Closing as not longer relevant. A new fix is underway.

**Pull request closed without merging**
