### PR TITLE
Add support to secured dashboard

### PR DESCRIPTION
**Pull request by dtrouillet**
Add support to secured dashboard with basic authentication.
If org.jobrunr.dashboard.login and org.jobrunr.dashboard.password properties are used, the basic authentication is enable with this informations.

Linked issue : #66

### CODE REVIEW

**Comment by rdehuyss** [comment]
Thx for this! I'll soon have a look!

**Comment by rdehuyss** [comment]
Hi @dtrouillet , sorry that I did not review this yet - some personal stuff going on.

I also want to make sure that if I accept this PR, it also works fine with the Pro version where there will be SSL support and support for third party login providers (e.g. GitHub, Google, ... ).

**Comment by dtrouillet** [comment]
Hi @rdehuyss ,

No problem. I don't have the pro version so I don't known how it works.

**Comment by esezeolivera** [comment]
Hey guys, great contribution here!!!
I am adding thiese values to my application.properties file:

org.jobrunr.dashboard.login=abcd
org.jobrunr.dashboard.password=abcd

But I am not getting the Basic Authentication to work. Am I missing anything else?

**Comment by esezeolivera** [comment]
Hi @rdehuyss,

any idea why I am not getting the authentication to pop up?

Thanks in advance and sorry to bother!

**Comment by rdehuyss** [comment]
Have you searched the repo? See [https://github.com/jobrunr/jobrunr/search?q=Authentication](https://github.com/jobrunr/jobrunr/search?q=Authentication).

Here is the relevant info: https://github.com/jobrunr/jobrunr/blob/master/framework-support/jobrunr-spring-boot-starter/src/main/java/org/jobrunr/spring/autoconfigure/JobRunrProperties.java#L177-L185

Depending on your editor, you would have autocomplete for your spring yml files.

**Comment by esezeolivera** [comment]
@rdehuyss thanks a million.

No I didn't look for the authentication bit in the repo. Very much appreciated. Thanks!!!

**Pull request merged**
